fixing INSTALL script with new repo organization

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -26,8 +26,6 @@ INSTALL_DIR=$PWD/local_install
 if [ -n "$LOGIN" ];
 then
   git remote set-url origin git+ssh://${LOGIN}@scm.gforge.inria.fr//gitroot/metalibm/metalibm-lugdunum.git && 
-  git config submodule.metalibm-lugdunum-core.url git+ssh://${LOGIN}@scm.gforge.inria.fr//gitroot/metalibm/metalibm-lugdunum-core.git && 
-  git config submodule.metalibm-lugdunum-functions.url git+ssh://${LOGIN}@scm.gforge.inria.fr//gitroot/metalibm/metalibm-lugdunum-functions.git || exit 1
 fi;
 
 # testing if branch is set, if so checkout a specific branch before populating the repo
@@ -36,21 +34,26 @@ then
   git checkout $BRANCH;
 fi;
 
-git submodule update --init --recursive && \ 
 cd $LOCAL_DIR && \
 mkdir -p $INSTALL_DIR || exit 1
 
 # if SOLLYA is already installed, change this variable to indicate the install 
 # containing both include and lib dirs where sollya can be found
-SOLLYA_INSTALL_DIR=$INSTALL_DIR
-# comment the following lines to use already installed sollya
-wget https://gforge.inria.fr/frs/download.php/33151/sollya-4.1.tar.gz && \
-tar -xzf sollya-4.1.tar.gz && \
-cd sollya-4.1/ && ./configure --prefix=$INSTALL_DIR && make -j 4 && make install  || exit 1
-
+if [ -n "$SKIP_SOLLYA_INSTALL" ];
+  echo "skipping sollya install"
+  if [ -z "$SOLLYA_INSTALL_DIR" ];
+    echo "ERROR: SOLLYA_INSTALL_DIR must be defined when skipping sollya install."
+  fi;
+else
+  SOLLYA_INSTALL_DIR=$INSTALL_DIR
+  # comment the following lines to use already installed sollya
+  wget https://gforge.inria.fr/frs/download.php/33151/sollya-4.1.tar.gz && \
+  tar -xzf sollya-4.1.tar.gz && \
+  cd sollya-4.1/ && ./configure --prefix=$INSTALL_DIR && make -j 4 && make install  || exit 1
+fi;
 # building and installing pythonsollya
 cd $LOCAL_DIR && \
-git clone https://gforge.inria.fr/git/metalibm/pythonsollya.git && \
+git clone https://gforge.inria.fr/git/metalibm/pythonsollya.git -b cythonsollya && \
 cd pythonsollya/ && LOCAL_INSTALL_DIR=$SOLLYA_INSTALL_DIR python setup.py build && python setup.py install --prefix $INSTALL_DIR  && \
 cd $LOCAL_DIR && \
 LOCAL_PYTHON_PATH=$(find $INSTALL_DIR -name pythonsollya | sed -e "s/pythonsollya//") && \
